###
GET http://localhost:8000


### Crear un user
POST http://localhost:8000/crea_nuevo_usuario
Content-Type: application/json

{
  "email": "del@del.com",
  "name": "del",
  "last_name": "del",
  "age": 37,
  "country_lada": "053",
  "phone": "053",
  "gender": "F",
  "url_avatar": "http://www.avatars/avatar.png",
  "password": "Hola123!"
}

### Recuperar todas los restaurantes
POST http://localhost:8000/api/verify/token

### Borrar una restaurante
GET http://localhost:8000/items

### Actualizar una restaurante
POST http://localhost:8000/api/github/users
Content-Type: application/json

{
  "country": "string",
  "page": "string"
}

### Actualizar una restaurante
POST http://localhost:8000/crea_nuevo_usuario/
Content-Type: application/json







