###
GET http://localhost:8000


### Crear un user
POST http://107.152.42.60:8000/crea_nuevo_usuario
Content-Type: application/json

{
   "email": "inicio@correo.com",
    "name": "Leo",
    "last_name": "Leo",
    "age": 31,
    "country_lada": "00",
    "phone": "051233",
    "gender": "F",
    "url_avatar": "http://www.avatars/avatar.png",
    "password": "Hola123!"
}

### Recuperar todas los restaurantes
POST http://localhost:8000/api/verify/token

### Borrar una restaurante
GET http://localhost:8000/items

### Actualizar una restaurante
POST http://localhost:8000/api/github/users
Content-Type: application/json

{
  "country": "string",
  "page": "string"
}

### Actualizar una restaurante
POST http://localhost:8000/crea_nuevo_usuario/
Content-Type: application/json







